### ISSUE TITLE
Upload got stuck at 15% because of KeyError

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#24]
DCOR Aid 0.5.10
Windows 10

An upload job got stuck during transfer at 15%. Closing DCOR-Aid and restarting it showed that an error had occured:

Traceback (most recent call last):
  File "C:\Users\labadmin\AppData\Local\DCOR Developers\DCOR-Aid\dcoraid\upload\job.py", line 358, in task_upload_resources
    exists = dataset.resource_exists(
  File "C:\Users\labadmin\AppData\Local\DCOR Developers\DCOR-Aid\dcoraid\upload\dataset.py", line 169, in resource_exists
    if resource[key] != resource_dict[key]:
KeyError: 'sp:cells:cell type'

**Comment by paulmueller** [comment]
FYI I only fixed the key error.
