### ISSUE TITLE
Compression of dataset failed due to MemoryError

### ISSUE THREAD

**Issue by B-Hartmann** [DCOR-dev/DCOR-Aid#40]
Windows 10 version 19.09
DCOR-Aid version 0.7.6

A dataset was supposed to be uploaded to DCOR, but during the compression, an error occured and the process didn't finish.

The error message:  
Traceback (most recent call last):
  File "dcoraid\worker\daemon.py", line 48, in run
    task()
  File "dcoraid\upload\job.py", line 353, in task_compress_resources
    compress(path_out=path_out, path_in=path)
  File "dclab\cli\task_compress.py", line 45, in compress
  File "dclab\rtdc_dataset\export.py", line 240, in hdf5
  File "dclab\rtdc_dataset\writer.py", line 153, in store_feature
  File "dclab\rtdc_dataset\writer.py", line 317, in write_image_grayscale
  File "numpy\core\_asarray.py", line 83, in asarray
MemoryError: Unable to allocate 25.3 GiB for an array with shape (1357715, 80, 250) and data type uint8

It looks like the compression was about to happen in the RAM instead of on the system hard drive like in previous versions.
The disk space should not be a problem, there is still 700 GB free on the main hard drive (where the Windows installation is located).

**Comment by paulmueller** [comment]
before:
https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/0.35.8/dclab/rtdc_dataset/write_hdf5.py#L78-L80

now:
https://github.com/ZELLMECHANIK-DRESDEN/dclab/blob/0.38.1/dclab/rtdc_dataset/writer.py#L338-L339

Looks like in the new version the "mask" array is copied into memory twice (multiplication by 255) instead of only once. This is probably what's causing the issue. I am working on a more memory-conserving implementation.

Thanks for reporting this.

**Comment by paulmueller** [comment]
This is fixed in dclab 0.38.2.
