### ISSUE TITLE
Error message when opening DCOR-Aid on Mac

### ISSUE THREAD

**Issue by jamie-rivercyte** [DCOR-dev/DCOR-Aid#77]
When I opened the app and chose 'playground' and clicked submit, this error popped up:

Unhandled exception in DCOR-Aid version 0.14.2:
Traceback (most recent call last):
  File "dcoraid/gui/wizard/__init__.py", line 84, in _finalize
    api_key = self.get_api_key()
  File "dcoraid/gui/wizard/__init__.py", line 143, in get_api_key
    return get_dcor_dev_api_key()
  File "dcoraid/gui/wizard/__init__.py", line 23, in get_dcor_dev_api_key
    api.get_user_dict()
  File "dcoraid/api/ckan_api.py", line 334, in get_user_dict
    userdata = self.get("user_show")
  File "dcoraid/api/ckan_api.py", line 298, in get
    rdata = self.handle_response(req, api_call)
  File "dcoraid/api/ckan_api.py", line 204, in handle_response
    raise APIAuthorizationError(msg)
dcoraid.api.errors.APIAuthorizationError: Authorization Error: message: Access denied (for 'user_show')

It looks like I'm missing an API key but the UI never asked me to provide one

**Comment by paulmueller** [comment]
The initial setup wizard should have asked you to sign in and create an API token. It is now possible again to create API tokens via the API (https://github.com/ckan/ckan/issues/7836).
So there seems to be something broken in DCOR-Aid
